apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
  namespace: gitlab-system
spec:
  chart:
    values:
      certmanager:
        install: false
      global:
        hosts:
          domain: $DOMAIN
          hostSuffix: gitlab-system
        ingress:
          configureCertmanager: false
    version: 6.5.3
